version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "qsh"
s3_prefix = "qsh"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

[default.build]
[default.build.parameters]
cached = true
parallel = true
